version: 2
jobs:
  python3:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout

      - run:
          name: Install container dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -qq -y git-lfs

      - run:
          name: Install python dependencies
          command: |
            mkdir -p venv
            virtualenv venv
            . venv/bin/activate
            set -o pipefail; pip install --upgrade -r requirements_dev.txt | cat

      - run:
          name: Show versions
          command: |
            . venv/bin/activate
            pip freeze

      - run:
          name: Pull test assets from Git LFS
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
            ssh git@github.com git-lfs-authenticate "${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}" download
            git lfs pull

      - run:
          name: Run tests
          when: always
          command: |
            . venv/bin/activate
            ./dev.py test

      - run:
          name: Check lint
          when: always
          command: |
            . venv/bin/activate
            ./dev.py lint

      - run:
          name: Check code format
          when: always
          command: |
            . venv/bin/activate
            ./dev.py black-check

workflows:
  version: 2

  on-commit:
    jobs:
      - python3

  daily:
    triggers:
      - schedule:
          cron: "0 17 * * *"
          filters:
            branches:
              only: master
    jobs:
      - python3
